# ------------------------------------------------------------- #
# Rutas
# ------------------------------------------------------------- #
dir:
  base: "/Users/alessiobocco/Documents/Maestria/Maestría Di Tella/Data-mining/TP"
  data: "/Users/alessiobocco/Documents/Maestria/Maestría Di Tella/Data-mining/TP/data"
  output: "/Users/alessiobocco/Documents/Maestria/Maestría Di Tella/Data-mining/TP/output"
# ------------------------------------------------------------- 

# ------------------------------------------------------------- #
# Worker
# ------------------------------------------------------------- #
workers: 6
# ------------------------------------------------------------- 
